# Numpy 

知らなかった機能についてメモ

In [2]:
import numpy as np

## 変換

In [10]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# 1D -> 3D
b = a.reshape(3, 3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# 3D -> 1D
# rabvel: 参照を返す
c1 = b.ravel()
c1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# 3D -> 1D
# flatten: コピーを返す
c2 = b.flatten()
c2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 参照、コピー

In [14]:
# 参照
b1 = b
print('b1\n', b1)

b1[0, 0] = 100
print('b1\n', b1)
print('b\n', b)

b1
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b1
 [[100   2   3]
 [  4   5   6]
 [  7   8   9]]
b
 [[100   2   3]
 [  4   5   6]
 [  7   8   9]]


参照では、参照した先の変数を編集すると参照元も編集される

In [15]:
# コピー
b2 = b.copy()
print('b2\n', b2)

b2[2, 2] = 900
print('b2\n', b2)
print('b\n', b)

b2
 [[100   2   3]
 [  4   5   6]
 [  7   8   9]]
b2
 [[100   2   3]
 [  4   5   6]
 [  7   8 900]]
b
 [[100   2   3]
 [  4   5   6]
 [  7   8   9]]


コピーでは、コピーした変数を編集しても、コピー元の変数は編集されない<br>
<font color=red>コピーを行うメソッドを使う方が安全、一次元配列を取得するならflatten を使う</font>

## 乱数

### 一様分布

In [32]:
np.random.seed(123)
np.random.rand(2, 3)

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646]])

In [29]:
# 整数値の一様分布
np.random.seed(123)
np.random.randint(1, 10, (4, 3)) # int [1, 9)  

array([[3, 3, 7],
       [2, 4, 7],
       [2, 1, 2],
       [1, 1, 4]])

In [30]:
# 小数値の一様分布
np.random.seed(123)
np.random.uniform(0.0, 5.0, (2, 3)) # float [0.0, 5.0)  

array([[3.48234593, 1.43069667, 1.13425727],
       [2.75657385, 3.59734485, 2.1155323 ]])

In [31]:
# uniform のデフォルトは [0.0, 1.0)
np.random.seed(123)
np.random.uniform(size=(2, 3)) # float [0.0, 5.0)

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646]])

### 正規分布

In [33]:
np.random.seed(123)
np.random.randn(2, 3)

array([[-1.0856306 ,  0.99734545,  0.2829785 ],
       [-1.50629471, -0.57860025,  1.65143654]])

## 単位行列

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 行列を指定値で埋める

In [35]:
np.full(3, 3.14)

array([3.14, 3.14, 3.14])

In [36]:
np.full((2,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

## 範囲指定で均等割データの作成

In [37]:
np.linspace(0, 1, 5) # 0 ~ 1 まで 5つに分割

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
# 0 ~ 3.14 までを 20分割したデータ、sin関数でグラフを描くときに便利
np.linspace(0, np.pi, 21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

## 要素間の差分

In [46]:
l = np.array([2, 2, 6, 1, 3])
np.diff(l)

array([ 0,  4, -5,  2])

## 分割

In [48]:
b3 = np.arange(0,9).reshape(3,3)
b3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
# 水平方向に２番目の配列を分割
np.hsplit(b3, [2])

[array([[0, 1],
        [3, 4],
        [6, 7]]),
 array([[2],
        [5],
        [8]])]

In [52]:
# 水平方向に１番目の配列以降を分割
np.hsplit(b3, [1])

[array([[0],
        [3],
        [6]]),
 array([[1, 2],
        [4, 5],
        [7, 8]])]

In [53]:
# 垂直方向に２番目の配列を分割
np.vsplit(b3, [2])

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]])]

In [54]:
# 垂直方向に１番目の配列以降を分割
np.vsplit(b3, [1])

[array([[0, 1, 2]]),
 array([[3, 4, 5],
        [6, 7, 8]])]

## 次元追加

In [55]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [56]:
a[np.newaxis, :]

array([[100,   2,   3,   4,   5,   6,   7,   8,   9]])

In [57]:
a[:, np.newaxis]

array([[100],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9]])