# Numpy 

<font color=blue>知らなかった機能についてメモ</font>

In [1]:
import numpy as np

## 変換

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 1D -> 3D
b = a.reshape(3, 3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# 3D -> 1D
# rabvel: 参照を返す
c1 = b.ravel()
c1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# 3D -> 1D
# flatten: コピーを返す
c2 = b.flatten()
c2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
text1 = np.array([['Hello'], ['World']])
text1

array([['Hello'],
       ['World']], dtype='<U5')

In [7]:
text2 = text1.flatten()
text2

array(['Hello', 'World'], dtype='<U5')

<font color=blue>「入力された複数の文章を結合して特徴量を取る」などの場合に使えるか。<br>
\[text1, text2, text3,...\] -> \[TEXT\]</font>

## 参照、コピー

In [8]:
# 参照
b1 = b
print('b1\n', b1)

b1[0, 0] = 100
print('b1\n', b1)
print('b\n', b)

b1
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b1
 [[100   2   3]
 [  4   5   6]
 [  7   8   9]]
b
 [[100   2   3]
 [  4   5   6]
 [  7   8   9]]


<font color=blue>参照では、参照した先の変数を編集すると参照元も編集される</font>

In [9]:
# コピー
b2 = b.copy()
print('b2\n', b2)

b2[2, 2] = 900
print('b2\n', b2)
print('b\n', b)

b2
 [[100   2   3]
 [  4   5   6]
 [  7   8   9]]
b2
 [[100   2   3]
 [  4   5   6]
 [  7   8 900]]
b
 [[100   2   3]
 [  4   5   6]
 [  7   8   9]]


<font color=blue>コピーでは、コピーした変数を編集しても、コピー元の変数は編集されない</font><br>
<font color=red>コピーを行うメソッドを使う方が安全、一次元配列を取得するならflatten を使う</font>

## 乱数

### 一様分布

In [10]:
np.random.seed(123)
np.random.rand(2, 3)

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646]])

In [11]:
# 整数値の一様分布
np.random.seed(123)
np.random.randint(1, 10, (4, 3)) # int [1, 9)  

array([[3, 3, 7],
       [2, 4, 7],
       [2, 1, 2],
       [1, 1, 4]])

In [12]:
# 小数値の一様分布
np.random.seed(123)
np.random.uniform(0.0, 5.0, (2, 3)) # float [0.0, 5.0)  

array([[3.48234593, 1.43069667, 1.13425727],
       [2.75657385, 3.59734485, 2.1155323 ]])

In [13]:
# uniform のデフォルトは [0.0, 1.0)
np.random.seed(123)
np.random.uniform(size=(2, 3)) # float [0.0, 5.0)

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646]])

<font color=blue>ある範囲にある数値を同じ確率で取得<br>
→果たして何に使おうか</font>

### 正規分布

In [14]:
np.random.seed(123)
np.random.randn(2, 3)

array([[-1.0856306 ,  0.99734545,  0.2829785 ],
       [-1.50629471, -0.57860025,  1.65143654]])

<font color=blue>
ある関数の実数値に正規分布からランダムに得た数値を足すことによって、<br>
機械学習のサンプルデータを得られる<br>
回帰の勉強に使えそう
</font>

## 単位行列

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 行列を指定値で埋める

In [16]:
np.full(3, 3.14)

array([3.14, 3.14, 3.14])

In [17]:
np.full((2,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

## 範囲指定で均等割データの作成

In [18]:
np.linspace(0, 1, 5) # 0 ~ 1 まで 5つに分割

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
# 0 ~ 3.14 までを 20分割したデータ、sin関数でグラフを描くときに便利
np.linspace(0, np.pi, 21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

<font color=blue>
グラフを描くときに使えそう
</font>

## 要素間の差分

In [20]:
l = np.array([2, 2, 6, 1, 3])
np.diff(l)

array([ 0,  4, -5,  2])

## 分割

In [21]:
b3 = np.arange(0,9).reshape(3,3)
b3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
# 水平方向に２番目の配列を分割
np.hsplit(b3, [2])

[array([[0, 1],
        [3, 4],
        [6, 7]]),
 array([[2],
        [5],
        [8]])]

In [23]:
# 水平方向に１番目の配列以降を分割
np.hsplit(b3, [1])

[array([[0],
        [3],
        [6]]),
 array([[1, 2],
        [4, 5],
        [7, 8]])]

In [24]:
# 垂直方向に２番目の配列を分割
np.vsplit(b3, [2])

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]])]

In [25]:
# 垂直方向に１番目の配列以降を分割
np.vsplit(b3, [1])

[array([[0, 1, 2]]),
 array([[3, 4, 5],
        [6, 7, 8]])]

## 次元追加

In [26]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [27]:
a[np.newaxis, :]

array([[100,   2,   3,   4,   5,   6,   7,   8,   9]])

In [28]:
a[:, np.newaxis]

array([[100],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9]])

<font color=blue>
次元の関係でエラーになる関数があったとき、次元追加や分割で解決できる時がありそう
</font>